-- Legacy cleanup script for target_quantity references
-- This script removes all remaining target_quantity references from migration files
-- These are historical artifacts and should not be run directly
-- Instead, they document what needs to be cleaned up

-- Files that need to be updated:
-- 1. database/01-setup-database.sql - Remove target_quantity column definition
-- 2. database/02-seed-data.sql - Remove target_quantity from INSERT statements
-- 3. database/03-fix-batches-rls.sql - Remove target_quantity comments
-- 4. database/create-complete-database.sql - Remove target_quantity references
-- 5. database/debug-batch-data.sql - Remove target_quantity from queries
-- 6. database/deploy-batch-fixes.sql - Remove target_quantity parameters
-- 7. database/fix-actual-quantity-issue.sql - Remove target_quantity references
-- 8. database/fix-batch-numbering-function.sql - Remove target_quantity parameters
-- 9. database/fix-function-signature.sql - Remove target_quantity parameters
-- 10. database/fix-target-quantity-null.sql - Remove target_quantity references
-- 11. database/migrate-to-actual-quantity.sql - Clean up migration notes
-- 12. database/sample-data-for-testing.sql - Remove target_quantity from INSERT
-- 13. database/sample-data-for-testing-fixed.sql - Remove target_quantity
-- 14. database/sample-data-simple.sql - Remove target_quantity
-- 15. database/test-api-response.sql - Remove target_quantity from queries

-- Note: These files are historical migration files and should be preserved for reference
-- The actual database schema has already been updated to use actual_quantity only
