-- TEMPORARY: Disable RLS for testing
-- Run this in Supabase SQL Editor to test without RLS

ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE bread_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE sales_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE production_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE shift_feedback DISABLE ROW LEVEL SECURITY;
ALTER TABLE qr_invites DISABLE ROW LEVEL SECURITY;
ALTER TABLE sessions DISABLE ROW LEVEL SECURITY;